frr version 10.8.0-dev-el10
frr defaults traditional
hostname H1
!
ip route 0.0.0.0/0 10.0.1.1
!
interface eth0.101
 ip address 10.0.1.2/30
 link-type vlan parent eth0 id 101
exit
!
router pim
 no autorp discovery
exit
!
