frr version 10.8.0-dev-el10
frr defaults traditional
hostname R1
!
interface eth0.100
 ip address 10.0.0.1/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 link-type vlan parent eth0 id 100
 qos bandwidth 20mbps
 service-policy output PARENT
exit
!
interface eth0.101
 ip address 10.0.1.1/30
 ip ospf area 0
 link-type vlan parent eth0 id 101
exit
!
router ospf
exit
!
access-list VOICE seq 5 deny 10.1.1.0/24
access-list VOICE seq 10 permit 10.0.0.0/8
access-list MGMT seq 5 permit ip 10.0.0.0 0.0.0.255 any
access-list WEB seq 5 permit ip 10.0.1.0 0.0.0.255 any
!
ipv6 access-list VOICE seq 5 permit 2001:db8:99::/48
!
class-map match-any VOICE
 match ip dscp ef
exit
!
class-map match-all MGMT
 match access-group name MGMT
 match ip dscp cs6
exit
!
class-map match-all WEB
 match access-group name WEB
exit
!
class-map match-all BULK
 match ip dscp cs1
exit
!
policy-map CHILD
 class BULK
  bandwidth percent 30
  queue-limit 200 packets
 exit
 class class-default
  bandwidth percent 70
 exit
exit
!
policy-map PARENT
 class VOICE
  bandwidth 5mbps
  max-bandwidth percent 50
  priority 0
  queue-limit 64 packets
 exit
 class MGMT
  bandwidth percent 5
  priority 1
 exit
 class WEB
  bandwidth percent 20
  priority 2
  service-policy CHILD
 exit
 class class-default
  bandwidth percent 10
  max-bandwidth 15mbps
 exit
exit
!
router pim
 no autorp discovery
exit
!
